---
name: hugo publish

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.69.0'

    - name: Build
      run: hugo
      # test run: hugo -t hugo-theme-learn

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        EXTERNAL_REPOSITORY: goetzrieger/goetzrieger.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        emptyCommits: false
        commitMessage: ${{ github.event.head_commit.message }}
